### ISSUE TITLE
Tournaments and Schedules Page - Searchability

### ISSUE THREAD

**Issue by IndiHoops** [Indivisiblehoops/indihoops#11]
I would like to have an advanced search by - 

Month

State

City

Event Operator

Event Title

**Comment by theonlychase** [comment]
For this one, I am going to have to change the way data is inputted. Reason is because right now the dates are using a date picker when people create events. The date picker for searching is awful. It loads slow and people will get impatient with it. I created a temporary solution for now to let people know they can search for everything in the input box.

**Comment by IndiHoops** [comment]
Noted thanks.
